# Generated by Django 4.1.2 on 2022-10-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slogan", models.TextField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name", "slogan"],
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the student name", max_length=200
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="groupmember",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="groupmember",
            name="group",
        ),
        migrations.RemoveField(
            model_name="groupmember",
            name="user",
        ),
        migrations.DeleteModel(
            name="Group",
        ),
        migrations.DeleteModel(
            name="GroupMember",
        ),
        migrations.AddField(
            model_name="club",
            name="member",
            field=models.ManyToManyField(
                help_text="Select a student to join the club", to="clubs.member"
            ),
        ),
    ]
