# Generated by Django 4.1.2 on 2022-10-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0004_club_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="club",
            name="slug",
        ),
        migrations.AlterField(
            model_name="club",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
