# Generated by Django 4.1.2 on 2022-10-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0005_remove_club_slug_alter_club_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="id",
            field=models.IntegerField(
                help_text="ID of the student",
                primary_key=True,
                serialize=False,
                verbose_name="Student ID",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="name",
            field=models.CharField(
                help_text="Enter the student name",
                max_length=200,
                verbose_name="Student Name",
            ),
        ),
    ]
