# Generated by Django 4.1.2 on 2022-10-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0006_alter_member_id_alter_member_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="id",
            field=models.IntegerField(
                help_text="ID of the student", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="name",
            field=models.CharField(help_text="Enter the student name", max_length=200),
        ),
    ]
